### ISSUE TITLE
Reorder CI actions: latest version first

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#1052]
Writing a quick test for #1051 to see if it passed for PHP 8 (I don't have a version set up yet locally) did not provide all the information I hoped for.  The CI build aborted after some tests/checks had failed.

I think it would thus be more useful to have the tests and checks run with highest versions first (both PHP and dependencies).  Those are usually the ones we are more interested in.

WDYT?

**Comment by oliverklee** [comment]
If we want to have feedback for all PHP versions, we can use `fail-fast: false` like here:
https://github.com/oliverklee/ext-oelib/blob/main/.github/workflows/ci.yml#L26

Then the job is run for the complete matrix, independent of whether some of the matrix elements have failed.

**Comment by JakeQZ** [comment]
> we can use `fail-fast: false`

That looks like a better solution.  We would probably only need it for unit tests (for now).  And probably only for `push` CI builds (not `PR`).  Is it possible to distinguish between `push` and `PR` so as to save some server CPU cycles for a failing PR build?

The rationale (as is probably already clear) is to be able to commit to a branch some additional tests which may fail in some environments, to find out exactly what environments, with having to install all of those environments on a development PC.

**Comment by oliverklee** [comment]
No, I don't think this is distinguishable. Our builds are so fast that one or more additional jobs for other PHP versions do not make much of a difference anyway, I think.

**Comment by oliverklee** [comment]
I have created PR #1053 for this.
