### ISSUE TITLE
Fix the CI builds

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1080]
https://github.com/MyIntervals/emogrifier/runs/2760545402?check_suite_focus=true

Possibly related to the latest Composer updates?

**Comment by JakeQZ** [comment]
I think this was a glitch on GitHub.  For about a week or so, no actions were running at all (or at least not reporting their result - e.g. #1076 still has "Some checks haven’t completed yet" after 13 days).

If the weekly scheduled build succeeds next week, we can probably close this.

**Comment by oliverklee** [comment]
It indeed was a glitch: I've just retriggered the `main` build, and it's green now. Closing.
