### ISSUE TITLE
Composer script for PHPUnit coverage report

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#1126]
I've read [this](https://phpunit.readthedocs.io/en/9.5/code-coverage-analysis.html), and still don't know how to get the report.  I'm sure it's a simple command line option, but can't find easily find it.

TBH, I was barely aware this PHPUnit feature existed.

Unless I'm mistaken, we should add a Composer script (command) to run PHPUnit with whatever command line option is needed to generate the report.  This will prompt developers on the project to have a look at it, perhaps initially out of idle curiosity, but potentially leading to improvements in the robustness of the unit tests.

**Comment by oliverklee** [comment]
Note for myself: https://github.com/eliashaeussler/cache-warmup/pull/327
