### ISSUE TITLE
Disable PHPUnit test ordering

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#1136]
PHPUnit has some kind of 'AI' feature that runs tests in a non-logical order it thinks might be more useful, base on what happened on the last test run.

It isn't more useful.  It's unpredictable, clearly doesn't work properly, and is a PITA.

We need to add the command line switch (whatever it is) that disables this non-intelligence - unless you think you can work with it - ?

**Comment by JakeQZ** [comment]
If working to fix failing tests, I like to focus on them one at a time.  I often use the `--stop-on-failure` flag for that purpose.  If suddenly PHPUnit decides it's going to run a different test first, I have no idea how to get it to run the test whose specific failure I was looking into.  I really struggle to see any point to this 'feature' of PHPUnit.

**Comment by JakeQZ** [comment]
Quick searching does not turn up the command line flag.  I know I read about this "feature", and am definitely seeing it in action, exhibited as nothing more than strange behaviour, so I hope there is a flag to disable it.

**Comment by oliverklee** [comment]
PHPUnit has three possible orderings for running the tests:

- in a fixed order (alphabetically by test file path, and within the test file from top to bottom)
- taken explicitly annotated dependencies between tests into account (enabled by `executionOrder="depends"` in the `phpunit.xml`)
- [random](https://phpunit.readthedocs.io/en/9.5/textui.html) (to uncover hidden test dependencies)
- [run failed tests first](https://stackoverflow.com/questions/7119886/re-run-last-failed-test-in-phpunit) (enabled by `executionOrder="defects"` in `phpunit.xml`)

So we need to disable/remove `executionOrder="defects"` in `phpunit.xml`. As we are not using dependency annotations for tests, we can also remove the `executionOrder` switch altogether, I think.

**Comment by JakeQZ** [comment]
> * [run failed tests first](https://stackoverflow.com/questions/7119886/re-run-last-failed-test-in-phpunit) (enabled by `executionOrder="defects"` in `phpunit.xml`)

Yep, that's it.

It's possible that because I'm sometimes running with `--stop-on-failure` and sometimes not, it's getting in a mess.  Unfortunately I have since closed the terminal session and have no logs.  However, it's a weird behaviour I have seen before, probably with previous versions of PHPUnit (like 8.x, based on memory).

With this option, when there are multiple failed tests, in what order are the failed tests run?  Is it defined?  (If not, maybe that's the issue.)

> So we need to disable/remove `executionOrder="defects"` in `phpunit.xml`. As we are not using dependency annotations for tests, we can also remove the `executionOrder` switch altogether, I think.

Perhaps.  But I don't want to make an unnecessary change for personal convenience if I'm approaching things the wrong way, or make changes that may compromise how other developers work, or how we run the tests most effectively as part of the CI build.

So I think the jury is still very much out until we have more evidence, unless there's an obvious improvement that could be made to the settings.
