### ISSUE TITLE
Officially add support for PHP 8.2

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1155]
We'll need to allow PHP 8.2 via `composer.json` as well.

@timwolla Would you be willing to create a PR for this change (including the corresponding changelog entry)?

**Comment by TimWolla** [comment]
I would recommend waiting until the feature freeze ([July, 19th](https://wiki.php.net/todo/php82)) for this. It's still possible that new RFCs pass until then.
