### ISSUE TITLE
Remove Dependabot

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#1174]
Dependabot appears to be a waste of our time.

All it seems to do is up the minimum requried version of PHPUnit whenever there is a new point release of that.  In the PR it creates it says "to permit the latest version".  This is completely wrong.  The latest point release version is always permitted because we use `^` not `=` for the version number in `composer.json`.

However, we run our CI and weekly tests with both `DEPENDENCIES=lowest` and `DEPENDENCIES=latest` (or suchlike).  So they will always be run with the latest version of PHPUnit, as well as an older version that a developer may have kicking around if they have not run `composer update` recently.

I see no need to constantly up the minimum version requirement for PHPUnit if the bugfixes in the point release are not relevant to us.

Whenever there's a new version of PHPUnit, we are asked to approve Dependabot's changes to enforce that that version is now used.  This is a drain on our time, that could be better spent elsewhere.

Also, having a wider allowed range of version numbers for dependencies surely gives us better testing coverage.  Thus, we should not be enforcing specific minimum versions unless we really need them (e.g. for bugfixes we actually need).

I suggest we remove it.

**Comment by oliverklee** [comment]
@JakeQZ You sound really frustrated.

I find it important that we keep our dependencies mostly up to date. Would you be willing to regularly check them (e.g., monthly) and provide a PR for updating them?

**Comment by JakeQZ** [comment]
Monthly wiuld be far too often.

Software updates tend only ever to break things, whilst only fixing the most obscure security vulnerabilities that haven't even been found in the wild.

If the Dbot's commit message was customizable, that would be a start.  The author clearly does not speak English as a first language.

**Comment by oliverklee** [comment]
We probably also can provide a PR to improve the commit messages: https://github.com/dependabot/dependabot-core

**Comment by JakeQZ** [comment]
> We probably also can provide a PR to improve the commit messages: https://github.com/dependabot/dependabot-core

Ideally it would be per-project customizable.  There's no point changing it otherwise.

**Comment by oliverklee** [comment]
> Monthly wiuld be far too often.

What would be a frequency for manually updating the dependencies in which you would be willing to do this?

**Comment by oliverklee** [comment]
And would you be willing to provide the PR to remove Dependabot?

**Comment by JakeQZ** [comment]
> @JakeQZ Oh dear. You sound really frustrated.

Yes, I was.  Very sorry about my outburst and the tone of my original text for this issue.  I honestly don't know what came over me.  I hope I have not caused offence, and, if I have, I can only now apologize for that too.

I've calmed down a bit now.  I've also completely reworded the OP for this issue - more rationally.

> I find it important that we keep our dependencies mostly up to date.

The `.phar` files we do need to keep updating, because they are effectively hard-coded.

If there was a bot that could keep updating those for us, that would be brilliant.

I am not actually convinced that using PHIVE is bringing any benefits.  It may actually be making maintenance more time-consuming.  I logged some issues aginast PHIVE a while ago, and was told that we should not be storing the `.phar`s under version control.  So we are doing that wrong, apparently.

In my edited OP, I've explained why I don't think we ever need to up the minimum version numbers of dependencies in `composer.json` unless there's an actual justifiable reason for doing so - e.g. if we need a specific fix to be included - and how having more lax requirements actually gives us better CI/testing coverage.

> What would be a frequency for manually updating the dependencies in which you would be willing to do this?

As and when required.  Or never.  Except for the `.phar`s which don't update themselves.

Composer will always, by default, install the latest and greatest that is compatible.  So we don't need to.

There is a new release of PHP every year (around December, with RTM* around September, and betas usually available on GitHub a bit before then).

We usually make a new release of Emogrifier to coincide with the new PHP release, because we need to allow the new PHP version in `composer.json`.

Historically we have deprecated and removed support for EOL PHP versions.  I'm not sure we need to do this so much now.  We were previously keen to drop support for old PHP versions so that we could use the type-safety language features introduced in PHP 7.0 and 7.1.  But now, If the software still works fine with EOL PHP versions, and there are no new language features we want to make use of, I don't think we should be attempting to police what server software the users of this package choose to deploy.

The WooCommerce team had some issues because they needed to support a wider range of PHP versions than we do.  They sorted it out and did not file a ticket here.  But I think we'd be more likely to get support tickets by dropping support for EOL PHP versions than we would for any issues that occur with those EOL versions - after all, they've stood the test of time.

> And would you be willing to provide the PR to remove Dependabot?

I can do that.  However, I'd like to be sure that we are in agreement.  So I've added the 'discussion' label to this issue for the time being.  I've touched on some other issues that are outside the original scope of this, and would welcome your thoughts on those too.

(*RTM = Release to Manufacturing.  Of course, there is no actual manufacturing here, but the metaphor applies: it's likely to be the final cut unless any issues are found.)

**Comment by JakeQZ** [comment]
cross-reference: #1172

**Comment by JakeQZ** [comment]
cross-reference: #1164

**Comment by JakeQZ** [comment]
> I'd like to be sure that we are in agreement. So I've added the 'discussion' label to this issue for the time being

There might not be anything more to actually discuss, but I'd like you to give it some thought before deciding where we are going.

**Comment by JakeQZ** [comment]
> > I'd like to be sure that we are in agreement. So I've added the 'discussion' label to this issue for the time being
> 
> There might not be anything more to actually discuss, but I'd like you to give it some thought before deciding where we are going.

I've given it a bit of thought, and still agree with my original thoughts.

IMO there is no point in Dependabot, and it is contrary to good software development practices:

- Because we run CI tests with both 'latest' and 'minumum', we get (IMO) more testing coverage by not upping the minumum version requirements;
- We don't need to up the point-release minimum version unless we need a specific bugfix -
  - We can do that manually as and when necessary;
- Being more lax about version requirements helps us avoid foistering version-hell-soup on others - users of our software that we need to support.

**Comment by JakeQZ** [comment]
> IMO there is no point in Dependabot, and it is contrary to good software development practices

I can't see any benefit of it.  Only downsides.

Microsoft seem to have totally lost the plot these days.  I would take any future offering on GitHub with a very big [pinch of salt](https://idioms.thefreedictionary.com/Pinch+of+salt).
