### ISSUE TITLE
set convertDeprecationsToExceptions="true" in phpunit.xml?

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#1181]
https://github.com/MyIntervals/emogrifier/pull/1180#issuecomment-1268076336

I think this is approprate for the CI build.

But for developers, it could be a PITA.

I think we need to distinguish between developer and release.

And not have things hampering development.

I need to occasionally run a build locally and test against some other software, without having the build failing due to e.g. some `error_log` calls (which will be rejected as settings currently are) to track down a problem.

We need both worlds.  Tight and strict as possible for testing for release.  But as loose as possible for use in development.  And maybe some way to move the slider between them.

**Comment by oliverklee** [comment]
We could have a separate PHPUnit configuration file for this with a dedicated Composer script, and add CI jobs that are allowed to fail. This allows us to also test this locally and get direct feedback on CI without blocking a merge.

What do you think, @JakeQZ?
