### ISSUE TITLE
Stop using the `no_trailing_comma_in_singleline_array` PHP-CS-Fixer rule

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1190]
```
Using cache file ".php-cs-fixer.cache".
SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS                                                                                                                      35 / 35 (100%)
Legend: .-no changes, F-fixed, S-skipped (cached or empty file), I-invalid file syntax (file ignored), E-error

Checked all files in 0.001 seconds, 14.000 MB memory used

Detected deprecations in use:
- Rule "no_trailing_comma_in_singleline_array" is deprecated. Use "no_trailing_comma_in_singleline" instead.
```

**Comment by JakeQZ** [comment]
Why do people keep changing the names of things for no good reason?

IMO the original name was actually better than the replacement.

Is there a new situation where you can have an optional trailing comma that is not in an array?  It would be news to me.

Once a name has been carefully chosen, you should stick with it, unless there is a very good reason to change it.  I don't see a good reason here.  If there isn't a good reason, the change is just wasting everyone's time.
