### ISSUE TITLE
 Disable HTML formatting by default

### ISSUE THREAD

**Issue by osbre** [MyIntervals/emogrifier#1213]
https://github.com/MyIntervals/emogrifier/blob/2923bdf5a78f2c8d65f961eb633bb4fd5c0cb46d/src/HtmlProcessor/AbstractHtmlProcessor.php#L243

Currently I'm solving it by using `::fromDomDocument` and passing custom document, wonder if there is a possibility of making it a built-in option/parameter?

**Comment by JakeQZ** [comment]
> (perhaps of the same type as provided)

I'm not 100% sure of this - if it's a Boolean and the value that ends up being provided is (say), `(int)1`, rejecting it may be over-the-top, particularly given that PHP is loosely-typed, and, e.g., values from SQL databases often end up as `string`s when they are supposed to be numbers.

**Comment by oliverklee** [comment]
My first question is: What's the usecase? Why would one want to now have nicely-formatted HTML (assuming that the HTML formatting gets mangled anyway due to the emogrification)?

**Comment by osbre** [comment]
@oliverklee I have a use-case for that: my app builds email layouts dynamically, and has a CSS rule that does `white-space: pre-wrap;`. When I use formatting - `DOMDocument`'s built-in formatter adds unnecessary whitespaces which my users then see. It makes a bug in my project, that's why I needed a way to disable formatting.

**Comment by oliverklee** [comment]
Then maybe we can completely turn off the autoformatting (so we don't need to have an option for this we'd have to maintain). What do you think?

**Comment by osbre** [comment]
Seems like a breaking change? Will it affect any of the current usages that people have?

**Comment by oliverklee** [comment]
I don't consider it to be breaking, as the exact way Emogrifier reformats the HTML is not guaranteed anyway.

**Comment by osbre** [comment]
Agreed, then it makes sense to remove it. (it doesn't feel intuitive to have formatting by default)
