### ISSUE TITLE
Fix composer-normalize on CI

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1246]
https://github.com/MyIntervals/emogrifier/actions/runs/7119015963/job/19383539691

Maybe we an upgrade of the development tools solves the problem.

**Comment by oliverklee** [comment]
Possibly related: https://github.com/shivammathur/setup-php/issues/799

**Comment by JakeQZ** [comment]
> Possibly related: [shivammathur/setup-php#799](https://github.com/shivammathur/setup-php/issues/799)

https://github.com/shivammathur/setup-php/issues/799#issuecomment-1843575027 suggests a workaround.
