### ISSUE TITLE
Add a fixer rule to always use the strict version of `in_array` & friends

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#1267]
Like this: https://github.com/MyIntervals/PHP-CSS-Parser/pull/584

**Comment by JakeQZ** [comment]
There might not be any - we may have already dealt with this - but worth double-checking.

Is there a PHP-CS-Fixer (or perhaps PHPStan/Psalm) rule we can add to cover this?

**Comment by oliverklee** [comment]
Indeed, there is such a fixer rule, and this ticket should be about that. (Damn you, copy'n'paste! ;-) ). I've updated the ticket title accordingly.
