### ISSUE TITLE
Use 'static::' instead of 'self::'.

### ISSUE THREAD

**Issue by Sam152** [MyIntervals/emogrifier#228]
Right now methods being 'private' instead of 'protected' makes it very hard for people extending emogrifier for their own purposes to replaces specific parts of the library.

Using 'self::' is very similar, instead of calling the method on the instance (which might subclass emogrifier), it always calls methods on the Pelago\ Emogrifier class.

**Comment by oliverklee** [comment]
I have concerns that making all private methods protected might make people depend on these methods (the naming and signature, and the existence of the methods in the first place), which would make refactoring harder. Or, we might break things for other people when we refactor the code.

It is very important to me that we are able to refactor our code.

What do you think about this, @Sam152?
