### ISSUE TITLE
Support @charset in the CSS

### ISSUE THREAD

**Issue by visioncan** [MyIntervals/emogrifier#296]
My css file with @charset "UTF-8" like:

``` css
@charset "UTF-8";
body {...} 
```

will output wraning:

``` sh
Warning: DOMXPath::query(): Invalid expression in /Users/../vendor/pelago/emogrifier/Classes/Emogrifier.php on line 353
```

**Comment by oliverklee** [comment]
https://developer.mozilla.org/en/docs/Web/CSS/@charset

Currently, Emogrifier does not support charset in the CSS yet. If you are using only ASCII characters in your CSS, you can safely remove the charset.

**Comment by JakeQZ** [comment]
We added support for dropping `@charset` rules without impacting CSS parsing in 2.0.

I don't think we'll ever support alternative charsets to UTF-8, which is the norm these days, unless that norm miraculously changes.

Can we close this as either 'fixed' or 'wontfix'?

**Comment by oliverklee** [comment]
Yes, let's close this.
