### ISSUE TITLE
Xpath errors not correctly handled

### ISSUE THREAD

**Issue by robertotremonti** [MyIntervals/emogrifier#317]
Running v0.1.1 and v1.1.1 I get hundreds of PHP warnings thats should be handled.

v0.1.1

```
PHP Warning:  DOMXPath::query() [<a href='domxpath.query'>domxpath.query</a>]: Invalid expression in [...]/Emogrifier.php on line 269
```

v1.0.0

```
PHP Warning:  DOMXPath::query(): Invalid expression in [...]/Emogrifier.php on line 294
PHP Warning:  DOMXPath::query(): Undefined namespace prefix in [...]/Emogrifier.php on line 294
PHP Warning:  DOMXPath::query(): xmlXPathCompOpEval: function not bound to undefined prefix div in [...]/Emogrifier.php on line 294
```

**Comment by oliverklee** [comment]
Hi @robertotremonti, thanks for the bug report. With which HTML and CSS does this problem occur? What would be the minimal HTML/CSS to reproduce the problem?

Does this problem also occur with the latest master?

**Comment by robertotremonti** [comment]
I'm converting a huge document containing hundreds of CSS rules.
Hard to minimize it.
Do you want me to attach it to this discussion?

**Comment by oliverklee** [comment]
No, we need a minimal example both to narrow down the cause as well as put it into a unit test. So someone needs to do the work of minimizing the example anyway.

**Comment by oliverklee** [comment]
I propose using a bisect-like approach: Cut half the CSS repeatedly until the problem disappears, then undo. Then cut from the other side. This should reduce it to a single rule/selector. This will take O(log(n)) time.

**Comment by robertotremonti** [comment]
I've just isolated two CSS rules that trigger the warnings.

1.
```
PHP Warning:  DOMXPath::query() [<a href='domxpath.query'>domxpath.query</a>]: Invalid expression in [...]/Emogrifier.php on line 294
```
```
.uk-overlay-area-content > :last-child {
  margin-bottom: 0;
}
```

2.
```
PHP Warning:  DOMXPath::query() [<a href='domxpath.query'>domxpath.query</a>]: Invalid expression in [...]/Emogrifier.php on line 723
```
```
@media (min-width: 768px) {
  .uk-dropdown:not(.uk-dropdown-stack) > .uk-dropdown-grid > [class*='uk-width-']:nth-child(n+2) {
    border-left: 1px solid #dddddd;
  }
}
```

**Comment by oliverklee** [comment]
Thanks for the minimized testcases.

Concerning the 2nd error: nth-child currently is not supported properly yet. Would you be willing to provide a pull request for any of these two errors (including the necessary unit tests)?

**Comment by robertotremonti** [comment]
I'll take a look as soon as possible.

**Comment by oliverklee** [comment]
This already should have been solved with the debug mode. @robertotremonti If this is still a problem with Emogrifier 2.0.0, please feel free to reopen this ticket.
