### ISSUE TITLE
CSS Selector :not() is not parsed

### ISSUE THREAD

**Issue by wimulkeman** [MyIntervals/emogrifier#356]
The following CSS is not parsed by Emogrifier.

`td.columns table:not(.button),
td.column table:not(.button),
th.columns table:not(.button),
th.column table:not(.button) {
  width: 100%; }`

The part which seems to produce a problem is :not(.button). There is no error produced from within Emogrifier.

In the old versions, the CSS would still be available in the stylesheet in the header of the mail, but not converted into inline CSS. In the newer versions of Emogrifier (1.1.0), this part of the CSS is also removed from the stylesheet in the header by Emogrifier, which produces a more default behavior, but disabled the usage of the CSS functionality completely.

The Symfony CSS Selector, suggested in https://github.com/jjriv/emogrifier/issues/287 seems to fix this problem with this https://github.com/symfony/css-selector/blob/master/Parser/Parser.php#L238.

**Comment by oliverklee** [comment]
Fixed by #431.
