### ISSUE TITLE
Move media queries to <body> instead of <head>

### ISSUE THREAD

**Issue by Gabe-SpotMe** [MyIntervals/emogrifier#358]
I'm loading in the contents of a css file and emogrifier is correctly moving all the media queries to a STYLE tag in the HEAD of the output.  Since most email clients strip out the HEAD, Foundation for Email recommends that the media queries be placed at the top of the BODY tag.  Is it possible to make that change or create a setting that will do that?

**Comment by oliverklee** [comment]
Hi @Gabe-SpotMe, do you have any links about the HEAD getting stripped in most email clients and about the requirement from Foundation? Thanks!

**Comment by Gabe-SpotMe** [comment]
Sure, here's their online inliner.  [](http://foundation.zurb.com/emails/inliner.html)
Take a look at the notes on the right of the page.

**Comment by oliverklee** [comment]
@Gabe-SpotMe Thanks!

**Comment by oliverklee** [comment]
@Gabe-SpotMe Would you be willing to create a pull request for this?

**Comment by Gabe-SpotMe** [comment]
I just put one up.  I'm a relatively novice developer so I apologize if I missed anything.  My changes worked in my tests though...

**Comment by oliverklee** [comment]
@Gabe-SpotMe Great!

Could you please add some unit tests that fail without your changes and pass with it? And could you please add a changelog line?

**Comment by Gabe-SpotMe** [comment]
I added the changelog line and added a note to the readme.  Unfortunately I've never written a unit test before so I'm not quite sure how to do that...

**Comment by oliverklee** [comment]
@Gabe-SpotMe I'll be glad to help you with the unit tests.

1. Have you already done a "composer install" with your local copy of this Repository? (see https://github.com/jjriv/emogrifier/blob/master/CONTRIBUTING.md#install-the-development-dependencies )
2. Have you already run the existing unit tests using "vendor/bin/phpunit Tests/"? (see https://github.com/jjriv/emogrifier/blob/master/CONTRIBUTING.md#unit-test-your-changes )

**Comment by Gabe-SpotMe** [comment]
I did the composer install and that worked fine.  But when I try to run existing unit tests I get the following error:
cannot open file "Tests/.php".

**Comment by oliverklee** [comment]
@Gabe-SpotMe Could you please post the exact command line you've used to run the tests? Thanks!

**Comment by Gabe-SpotMe** [comment]
I'm running Windows 10.  I navigated to the emogrifier/vendor/bin directory and tried to run 'phpunit Tests/'

it then shows the following error:
cannot open file "Tests/.php".

If I run just 'phpunit' at that same folder, it does successfully give me PHPUnit 4.7.27 help content.

**Comment by oliverklee** [comment]
You'll need to be in the package's root directory and then run:
```
vendor/bin/phpunit Tests/
```

(Composer bin commands expect to be called from within the package root, not from the vendor/bin/ directory.)

**Comment by oliverklee** [comment]
On Windows, you also might need to replace the forward slashes with backslashes (depending on which shell you're using).

**Comment by Renkas** [comment]
Any progress on this?

**Comment by oliverklee** [comment]
@Renkas I'm currently waiting for a reply by @Gabe-SpotMe.

@Renkas Would you be willing to take over?

**Comment by oliverklee** [comment]
Fixed by #396.
