### ISSUE TITLE
Remove the !important flag from CSS rules

### ISSUE THREAD

**Issue by maoxiong** [MyIntervals/emogrifier#378]
Outlook doesn't support the !important tag in any inline styles, so this should be removed. (If the !important flag is used, it actually ignores the whole rule!)

There is no need for it anyway, as the stylesheets are stripped out anyway.

See: https://www.campaignmonitor.com/blog/email-marketing/2010/05/outlook-2007-and-the-inline-important-declaration/

**Comment by oliverklee** [comment]
Hi @maoxiong, are you referring to the style tags that are kept in the HEAD section of the document or to the non-CSS styles in the HTML nodes that Emogrifier creates out of the CSS rules?

**Comment by oliverklee** [comment]
And could you please post/attach the HTML and CSS which you put in, the actual resulting HTML, and the HTML that you would expect to get generated? Thanks!

**Comment by maoxiong** [comment]
Hi Oliver,

@oliverklee , Sure this is an easy one. Example attached.

Emogrifier is correctly changing the DIV's inline style, but but also putting the "!important" part in, thus making it ignored in Outlook.

As the styles are all inlined  (and the original head style tags stripped) - there is no need to leave that !important in there anyway :)

Of course the media query css in the style tags should be left as is, but that bit is working fine.
[noimportant.txt](https://github.com/jjriv/emogrifier/files/864064/noimportant.txt)

**Comment by oliverklee** [comment]
Thanks!

**Comment by oliverklee** [comment]
Would you be willing to create a pull request for this (including unit tests and the fix)?

**Comment by maoxiong** [comment]
Hi Oliver - I would love to be able to say yes, but I have no clue how to do that :(

I'm good at finding bugs, but not so good at fixing them! haha.

**Comment by oliverklee** [comment]
This was fixed in #420.
