### ISSUE TITLE
XPath error with input[type=text]

### ISSUE THREAD

**Issue by laurensschuitemaker** [MyIntervals/emogrifier#381]
Hi,

I noticed when my CSS contains input[type=text], it throws this error:
DOMXPath::query(): Invalid expression in selector >> div.form-field input[type="submit"] << in Emogrifier.php on line 370

How can I solve this?

Thanks

**Comment by oliverklee** [comment]
Hi @laurensschuitemaker, this looks like a bug. Could you please post the full CSS rule that triggers this error?

**Comment by laurensschuitemaker** [comment]
Hi @oliverklee, sure:
div.form-field input[type=text],
div.form-field input[type=password],
div.form-field textarea,
div.form-field select{
	width: 200px;
	padding: 3px;
	border: 1px solid #B6B6B6;
	outline-color: #048399;
}

This also doesn't work (same error):
.form-columns-switcher .column-switcher:nth-child(3n + 1){}

Thanks!

**Comment by oliverklee** [comment]
Thanks!

**Comment by oliverklee** [comment]
Fixed by 2c2b7853e35c8d03b301661bbe3732d7569d5ba2.
