### ISSUE TITLE
Support > :first-child and > :last-child

### ISSUE THREAD

**Issue by ghost** [MyIntervals/emogrifier#384]
The following selectors seem to generate invalid XPath, crashing the whole parser:

With `:first-child`:
```
  .an-element > :first-child {
    /** Any rules **/
  }
```

With `:last-child`:
```
  .an-element > :last-child {
    /** Any rules **/
  }
```

The issue is closely related for these two. It causes an `InvalidArgumentException` to be thrown (at https://github.com/jjriv/emogrifier/blob/master/Classes/Emogrifier.php#L1532)

**Comment by joeworkman** [comment]
`:not(.class)` selectors also trigger this error.

**Comment by oliverklee** [comment]
@joeworkman I've entered #469 for adding support for `:not(.class)`.
