### ISSUE TITLE
Invalid expression in selector >> <<

### ISSUE THREAD

**Issue by mcblum** [MyIntervals/emogrifier#397]
Hello! Sorry if this is a dumb question, but I'm having an issue where if I use more than one css style I get the error:

```
DOMXPath::query(): Invalid expression in selector >> << in /www/Symposia/symposia/vendor/pelago/emogrifier/Classes/Emogrifier.php on line 370
```

If I do `$css = 'h1 {font-size: 48px; font-weight: 400; margin: 0;}'` is works just fine but if I do `$css = 'h1 {font-size: 48px; font-weight: 400; margin: 0;}, h2 {font-size: 24px; font-weight: 400; margin: 0;}, p {margin: 0;}'` it fails. Any idea what I'm doing wrong?

**Comment by mcblum** [comment]
I am the dumb. I have fired myself.

**Comment by mcblum** [comment]
Whelp, never mind. I did figure out that I was using commas in the CSS, but even after fixing that when I went back to trying to inline the actual rendered view I'm now getting:

```
(1/1) ErrorExceptionTrying to get property of non-object
--
in Emogrifier.php (line 314)
at HandleExceptions->handleError(8, 'Trying to get property of non-object', '/www/Symposia/symposia/vendor/pelago/emogrifier/Classes/Emogrifier.php', 314, array('xmlDocument' =>object(DOMDocument), 'innerDocument' => object(DOMDocument)))in Emogrifier.php (line 314)
```

Any ideas what I may be doing wrong? The html that's being inlined is a rendered Laravel view and without inlining it works as expected.

**Comment by oliverklee** [comment]
Hi @mcblum, could you please some minimal HTML and CSS to reproduce the issue?

And which version of Emogrifier are you using?

Thanks!

**Comment by Glavic** [comment]
Why do you have commas between rules?
Remove them:

`$css = 'h1 {font-size: 48px; font-weight: 400; margin: 0;} h2 {font-size: 24px; font-weight: 400; margin: 0;} p {margin: 0;}'`

**Comment by oliverklee** [comment]
Closing as the CSS is invalid.
