### ISSUE TITLE
Release version 2.0.0

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#421]
I'd like to make the next release version 2.0.0 instead of 1.3.0 as the merged changes (and the pending PRs) could be considered to be breaking.

I'll then also drop compatibility with PHP 5.4 (as announced in the changelog):

@jjriv What do you think about this? Would you be okay with this?

**Comment by jjriv** [comment]
I think this is great. Please go ahead and do it. Also, let me know once it's done and i'll promote it on our blog and social media. And if there are any noteworthy changes to mention, tell me and I'll include those in the announcement as well.

**Comment by maoxiong** [comment]
Even though 5.4 compatibility will be dropped, will it still work unofficially?

Some of the externally purchased codebase I use is ioncube encoded and doesn't work with anything higher than 5.4!!

**Comment by oliverklee** [comment]
Yes, it will probably work, but Composer will not install the package on PHP 5.4. You'll then need to manually copy the class file.
