### ISSUE TITLE
Cyrillic characters get mangled

### ISSUE THREAD

**Issue by reimax** [MyIntervals/emogrifier#424]
Hi, my code:

`
require_once 'emogrifier/vendor/autoload.php';
$emogrifier = new \Pelago\Emogrifier();

$emogrifier->setHtml($message_text);
$message_text = $emogrifier->emogrify();
`
as a result, I enclose a document with an incorrect encoding:
�������

if delete $message_text = $emogrifier->emogrify();, document charset correct. there is cyrillic in the document. project in utf-8 charset, mb_internal_encoding() set utf-8. how fix this?

**Comment by oliverklee** [comment]
Hi @reimax, thanks for the bug report! Could you please upload the source HTML and the resulting HTML somewhere and post the links?

And if you have time, could you please reduce the HTML as much as possible so that the bug still occurs (and the HTML still is valid), and the document is as small as possible? This will help narrow down the problem. Thanks!

**Comment by reimax** [comment]
Here is a small example of a letter that I download from the mail via imap.

after use emogrifier

`
<div id="divtagdefaultwrapper" style="font-size: 12pt; color: #000000; font-family: Arial,Helvetica,sans-serif;" dir="ltr"><p>Здравствуйте Алена,</p><p><br></p><p>Если заключаем договор то�оплата на р/с.</p><p>Другие способы: перевод на webmoney.</p></div>
`
before use emogrifier

`
<div id="divtagdefaultwrapper" style="font-size: 12pt; color: #000000; font-family: Arial,Helvetica,sans-serif;" dir="ltr"><p>Здравствуйте Алена,</p><p><br></p><p>Если заключаем договор то оплата на р/с.</p><p>Другие способы: перевод на webmoney.</p></div>
`

i check charset via mb_detect_encoding() and before and after utf-8.

**Comment by oliverklee** [comment]
Hi @reimax Thanks! Could you please upload both files somewhere so the exact encoding and the HTML tags are preserved? Thanks!

**Comment by reimax** [comment]
done! create link

**Comment by reimax** [comment]
i add meta tag with charset=utf-8 in my html code and roblem was solved

**Comment by oliverklee** [comment]
Thanks for the feedback. I'm glad to read this.

So can we close this issue, or do you still a problem in Emogrifier that should be fixed?

**Comment by reimax** [comment]
Thanks  for help!
