### ISSUE TITLE
Invalid / unrecognized CSS selectors in media query blocks are not handled

### ISSUE THREAD

**Issue by zoliszabo** [MyIntervals/emogrifier#441]
Invalid / unrecognized (not implemented) CSS selectors from within media query blocks are not handled and they are wrongfully causing a `\RuntimeException`.

**Comment by oliverklee** [comment]
This indeed should only throw an exception in debug mode, and be silently ignored in non-debug mode.

I see there's already a branch for this. Looking forward to reviewing the PR! :heart:

**Comment by zoliszabo** [comment]
Fixed with PR https://github.com/MyIntervals/emogrifier/pull/442.
