### ISSUE TITLE
Update the selector regexp to match the spec

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#449]
https://www.w3.org/TR/css3-selectors/#attribute-selectors

**Comment by JakeQZ** [comment]
@oliverklee, I presume this refers to the regex in `Emogrifier::$xPathRules` used (indirectly) by `Emogrifier::translateCssToXpath()`.  If so, and given `Emogrifier` will be deprecated in favour of `CssInliner` which now uses the Symfony CssSelector component instead, I suggest that we don't attempt further fixes to `Emogrifier::translateCssToXpath` and can close this?

**Comment by oliverklee** [comment]
Yes, agreed. Closing.

And thanks for digging through the list of open tickets, @JakeQZ! :heart:
