### ISSUE TITLE
Add Zoli Szabó as maintainer

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#450]
Hi @zoliszabo, you have provided quite a lot of very-high quality PRs for Emogrifier.

Would you like to become a co-maintainer of this project?

This would mean that you could review and merge PRs. And we'd also add you as an `@author` to the files, mention you as a maintainer in the README, and add you as a developer to the `composer.json`. And if that's okay for you, we'd also proudly announce this on Twitter & Co.

(If you accept this, we'll need a valid email address.)

What do you think?

**Comment by oliverklee** [comment]
cc: @jjriv

**Comment by zoliszabo** [comment]
Hi @oliverklee! I am honored to receive such a role on the project - I will of course accept it. It means so much for me, because Emogrifier is the project that made me really want to contribute to open source. Contributing is the only way I can give back a little for the large amount of work you guys did.
Thank you!

PS: my email address is zoli.szabo+github@gmail.com.

**Comment by oliverklee** [comment]
Great! :heart:

**Comment by oliverklee** [comment]
And reading that Emogrifier that motivated you to contribute to open source makes me happy!

What is your Twitter handle (so that we can mention you)?

**Comment by zoliszabo** [comment]
@SzZoli

**Comment by jjriv** [comment]
Welcome to the team @zoliszabo and thank you for your contributions. Let me know if you guys need me to do anything to finalize this request.

**Comment by oliverklee** [comment]
I've just posted a tweet: https://twitter.com/oliklee/status/946878804357771264

**Comment by oliverklee** [comment]
@zoliszabo As I'm not very familiar with Romanian names, I'll ask: "Zoli" is your first name?

**Comment by zoliszabo** [comment]
@jjriv Thank you for welcoming me to the team! I'm glad to become part of it.

@oliverklee Actually, I am a Hungarian born in the heart of Romania. And yes, "Zoli" is my first name (nickname for "Zoltán"). :)
