### ISSUE TITLE
Move the GitHub oAuth token from .travis.yml to the repository settings

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#462]
According to https://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings, secret environment variables that are the same across all branches and builds should be set in the repository settings, not in the `.travis.yml`.

@jjriv As it's your oAuth token, would you be willing to take care of this?

**Comment by jjriv** [comment]
I'm happy to help, but not sure what to do. Could you tell me the steps and I'll take care of it?

**Comment by oliverklee** [comment]
1. look up the unencrypted value for the `GITHUB_COMPOSER_AUTH` environment variable
2. go to https://travis-ci.org/MyIntervals/emogrifier/settings
3. add a `GITHUB_COMPOSER_AUTH` environment variable with the value you've looked up (and make sure to keep "Display value in build log" turned off)
4. Create a PR to remove the env>global>secure variable from `.travis.yml`
5. Check if the build still is green, and read it to see whether the environment variable gets set/used

**Comment by oliverklee** [comment]
Fixed in f18225faee69fb40875317758f2263eb60d8176f. Thanks, @jjriv!

**Comment by jjriv** [comment]
You are welcome. Feel free to clean up anything if I didn't name it so well.

____________________________________________________________________

John Reeve
jreeve@pelagodesign.com<mailto:jreeve@pelagodesign.com>
Intervals | Web-based Time, Task & Project Management | www.myintervals.com<http://www.myintervals.com>
____________________________________________________________________
