### ISSUE TITLE
Versions 3.0.0/4.0.0, refactoring, new classes

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#479]
Hi @jjriv and @zoliszabo, this is what I have in mind for Emogrifier 2.1.0, 3.0.0 and 4.0.0. Looking forward to your thoughts on this!

# Complexity and features

Generally, I'd like to get the Emogrifier class (back) to do exactly one thing, and do it well. This "one thing" is converting CSS files and `style` elements to inline CSS attributes. Other things should go into separate classes or packages, and may or may not be the responsibility of the Emogrifier project.

# Versions

## Emogrifier 2.1.0
I'd like everything which we're planning to remove in Emogrifier 3.0.0 to be marked as deprecated in Emogrifier 2.1.0 so people have one version in which they can see in their IDE that they're using something that is going to go away soon.

## Emogrifier 3.0.0
In this version, I'd like to drop the functionality which we have deprecated in version 2.1.0, and offer a replacement for some of these removed features. I'd like the Emogrifier class to not use any other Composer-autoloaded classes at this point, i.e., version 3.0.0 would be the last version that can be directly `require`d (without Composer), which is what some projects do.

For this version, Emogrifier will also require PHP >= 5.6, i.e., it will not require PHP 7 yet.

## Emogrifier 4.0.0
This version will require PHP 7, and it needs to be loaded via the Composer autoloader so that it can use other Composer-autoloaded classes and also make use of other Composer packages.

# Classes and architecture

## HtmlMinifier

For Emogrifier 2.1.0 or 3.0.0, I'd like to create a class like this:

```php
abstract class AbstractHtmlProcessor
{
    /**
     * Takes some HTML and directly converts it into an DomDocument.
     */
    public function __construct(string $unprocessedHtml);

    /**
    * Renders the processed HTML
    */
    public function render(): string;
}
```

We then can have several sub classes (which will replace some of the non-core Emogrifier functionality) that can be used like this:

```php
$emogrifier = new Emogrifier($html, $css);
$emogrifiedHtml = $emogrifier->process();
$minifiedHtml = (new HtmlMinifier($emogrifiedHtml))->removeInvisibleNodes()->removeClassAttributes()->render();
$retroHtml = (new new CssToAttributeConverter($minifiedHtml))->convertCssToAttributes()->render();

```

There'll be also a `HtmlNormalizer` that basically is just a subclass of `AbstractHtmlProcessor` that only normalizes the HTML (add document type, ensure UTF-8, ensure HTML, HEAD and BODY tags). So the functionality should be in the superclass, i.e., `HtmlMinifier` and `CssToAttributeConverter` will also normalize the HTML.

There'll be also a class `ExposingHtmlProcessor` that will provide access to the inner DomDocument.

For Emogrifier 2.1.0/3.0.0, we then can refer users to use the new classes instead of the deprecated methods.

And for Emogrifier 4.0.0, Emogrifier will use the `ExposingHtmlProcessor` to take care of normalizing the HTML.

It will also use 
Hi @jjriv and @zoliszabo, this is what I have in mind for Emogrifier 2.1.0, 3.0.0 and 4.0.0. Looking forward to your thoughts on this!

# Complexity and features

Generally, I'd like to get the Emogrifier class (back) to do exactly one thing, and do it well. This "one thing" is converting CSS files and `style` elements to inline CSS attributes. Other things should go into separate classes or packages, and may or may not be the responsibility of the Emogrifier project.

# Versions

## Emogrifier 2.1.0
I'd like everything which we're planning to remove in Emogrifier 3.0.0 to be marked as deprecated in Emogrifier 2.1.0 so people have one version in which they can see in their IDE that they're using something that is going to go away soon.

## Emogrifier 3.0.0
In this version, I'd like to drop the functionality which we have deprecated in version 2.1.0, and offer a replacement for some of these removed features. I'd like the Emogrifier class to not use any other Composer-autoloaded classes at this point, i.e., version 3.0.0 would be the last version that can be directly `require`d (without Composer), which is what some projects do.

For this version, Emogrifier will also require PHP >= 5.6, i.e., it will not require PHP 7 yet.

## Emogrifier 4.0.0
This version will require PHP 7, and it needs to be loaded via the Composer autoloader so that it can use other Composer-autoloaded classes and also make use of other Composer packages.

# Classes and architecture

## HtmlMinifier

For Emogrifier 2.1.0 or 3.0.0, I'd like to create a class like this:

```php
abstract class AbstractHtmlProcessor
{
    /**
     * Takes some HTML and directly converts it into an DomDocument.
     */
    public function __construct(string $unprocessedHtml);

    /**
     * Renders the processed HTML
     */
    public function render(): string;
}
```

We then can have several sub classes (which will replace some of the non-core Emogrifier functionality) that can be used like this:

```php
$emogrifier = new Emogrifier($html, $css);
$emogrifiedHtml = $emogrifier->process();
$minifiedHtml = (new HtmlMinifier($emogrifiedHtml))->removeInvisibleNodes()->removeClassAttributes()->render();
$retroHtml = (new new CssToAttributeConverter($minifiedHtml))->convertCssToAttributes()->render();

```

There'll be also a `HtmlNormalizer` that basically is just a subclass of `AbstractHtmlProcessor` that only normalizes the HTML (add document type, ensure UTF-8, ensure HTML, HEAD and BODY tags). So the functionality should be in the superclass, i.e., `HtmlMinifier` and `CssToAttributeConverter` will also normalize the HTML.

There'll be also a class `ExposingHtmlProcessor` that will provide access to the inner DomDocument.

For Emogrifier 2.1.0/3.0.0, we then can refer users to use the new classes instead of the deprecated methods.

And for Emogrifier 4.0.0, Emogrifier will use the `ExposingHtmlProcessor` to take care of normalizing the HTML.

It will also use use the Symfony selector component for converting CSS selectors to Xpath rules.

# Feedback questions

- Does this approach make sense to you?
- Is the suggested API for the `HtmlProcessor` perfect (including providing the HTML in the constructor, the fluent interface), or is there anything that should be improved?
- Is the naming perfect, or is there anything that should be improved?

**Comment by jjriv** [comment]
@oliverklee I don't have any improvements I would suggest. This proposal makes sense to me. I think it's a huge improvement for Emogrifier. Thanks for heading it up!

**Comment by zoliszabo** [comment]
@oliverklee I also think this proposal is as good as it gets. Eventual imperfections - if any - will come up during the implementation, but it is perfect for setting the goal.

I personally like the method chaining, it would be a nice touch to be able to set options on the new classes this way.

Since we are preparing a collection of classes, one more thing I thought of (but it may be out of scope or too much) is to make "Emogrifier" the name of the entire collection (i.e. it would transform into a namespace) and rename the current Emogrifier class to CssInliner or similar:
`\Pelago\Emogrifier\CssInliner`, `\Pelago\Emogrifier\HtmlMinifier`, `\Pelago\Emogrifier\CssToAttributeConverter` etc.

What do you guys think?

**Comment by oliverklee** [comment]
I like the idea with the sub-namespace and the new class name `CssInliner`. We then should deprecate the old class and add an alias to so that code using the old class will still work. @jjriv What are your thought on this?

**Comment by oliverklee** [comment]
Now that we agree on the roadmap, some reviews of #473 and #474 would be great!

**Comment by jjriv** [comment]
I like that idea of making Emogrifier the name of the collection. You could also take out the "Pelago" if you wanted to simplify things. That way it would just be `\Emogrifier\CssInliner`

**Comment by zoliszabo** [comment]
> We then should deprecate the old class and add an alias to so that code using the old class will still work.

👍

> You could also take out the "Pelago" if you wanted to simplify things. That way it would just be \Emogrifier\CssInliner

AFAIK the de facto standard is to use namespaces in the form of `\VendorName\PackageName\...`, so I would vote for keeping `Pelago` as vendor. Or deprecate it in favor of `MyIntervals`?

**Comment by zoliszabo** [comment]
Also, what about restructuring the folders a bit to comply with https://github.com/php-pds/skeleton/blob/1.0.0/README.md?

**Comment by oliverklee** [comment]
> AFAIK the de facto standard is to use namespaces in the form of \VendorName\PackageName\..., so I would vote for keeping Pelago as vendor. 

I agree - that's also what I know about the Composer naming schema.

@jjriv Which vendor namespace should we use? Keep Pelago or switch to MyIntervals?

**Comment by oliverklee** [comment]
> Also, what about restructuring the folders a bit to comply with https://github.com/php-pds/skeleton/blob/1.0.0/README.md?

Thanks! Sounds good at a first glance. I'll read up on it and then hopefully will have an informed opinion on this.

**Comment by jjriv** [comment]
I did not realize there was a standard. Let's keep it as Pelago. That is the name of the company and it's what we've always used.

**Comment by oliverklee** [comment]
I've read up on the PHP PDS. Let's do this. I've created ticket #489 for this.

Closing this ticket here as we have come to an agreement on all points, if I see this correctly.
