### ISSUE TITLE
Drop disableInvisibleNodeRemoval

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#482]

**Comment by burzum** [comment]
@oliverklee why was  this removed? Can I just remove it from our code without side effects?

**Comment by JakeQZ** [comment]
Hi @burzum 

The feature was not actually removed, but moved to a separate class `HtmlPruner`.

If you were previously calling `disableInvisibleNodeRemoval` then you were disabling the feature anyway so should expect the same functionality with 3.0.

We have moved 'side' functionality to separate classes such that the new `CssInliner` class does just that: inlines CSS; nothing more; nothing less.

But the other functionality is still available via the separate classes.  Please see the readme.
