### ISSUE TITLE
Create an Emogrifier twitter bot

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#490]
As a small learning project, I'd like to create a twitter bot that retweets all tweets with "Emogrifier" in them. I plan to follow the instructions from https://dev.to/omarhashimoto/how-to-build-a-simple-twitter-bot-in-17-lines-ofcode-2aan for this.

@jjriv Would that be okay with you?

And what should we name the bot? What about "Emogrifier bot"/`@emogrify_bot`?

**Comment by jjriv** [comment]
Yes, that is OK with me. I went ahead and claimed @emogrifier. I'll email you the password seperately.

**Comment by oliverklee** [comment]
Thanks!

**Comment by oliverklee** [comment]
Closing as Twitter is no longer relevant.
