### ISSUE TITLE
Incorrect style property order with multiple mixed individual and shorthand properties

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#508]
The following CSS
```
p { margin: 1em; margin-top: 0; }
.big p { margin: 2em; }
```
when applied to the HTML
```
<div class="big">
  <p>Some text</p>
</div>
```
results in
```
  <p style="margin: 2em; margin-top: 0;">Some text</p>
```
The `margin-top: 0` should either be before `margin: 2em` or (as an optimization in this case) not present at all.

**Comment by JakeQZ** [comment]
The issue arises from the behaviour of `array_merge` in `generateStyleStringFromDeclarationsArrays`.  When a property is present in both `$oldStyles` and `$newStyles`, its position in the resultant array comes from its position in `$oldStyles`, though there may be a later shorthand or individual property variant it should now be overriding.

To resolve this and maintain correct ordering, I propose:
- Move `$combinedStyles = array_merge(...)` to after the first `foreach` loop;
- In the loop either `unset($newStyles[$attributeName])` or `unset($oldStyles[$attributeName])` depending which should prevail;
- Change the cache key to `serialize([$oldStyles, $newStyles])`, since the result of the `array_merge` would no longer be available initially.

I'd suggest the possible optimization of eliminating individual styles that are overridden with shorthand styles be addressed as a separate issue.

**Comment by oliverklee** [comment]
@JakeQZ Sounds good. Would you be willing to tackle this bug?

**Comment by JakeQZ** [comment]
@oliverklee Yes, I have already confirmed the proposed fix works...

**Comment by oliverklee** [comment]
@JakeQZ #511 fixed this completely, so we can close this ticket, right?

**Comment by JakeQZ** [comment]
Yes, am closing.  I'll create a separate issue for the optimization.
