### ISSUE TITLE
Hotmail/Live drops margin properties with any negative component

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#509]
Consider the following CSS:
```
table {
  border-spacing: 1em 0;
  margin: 1em -1em;
}
```
The author has intended a vertical margin above/below tables, and a negative horizontal margin to compensate for the border spacing being applied to the outside edge of the table as well as between table cells.

However, when viewed in the Hotmail/Live webmail client, the margin property, even in an inline style attribute, is discarded due to the presence of negative values.  The degradation could be mitigated somewhat if the inline style was `margin: 1em 0; margin 1em -1em;` - with the first value as a fallback for such clients dropping the second, so the end result is closer to that intended.

**Comment by JakeQZ** [comment]
It's been suggested that such non-core functionality should go into a HtmlProcessor class (#479), yet to be implemented.  This functionality would require access to the DOM and XPath and ideally also `parseCssDeclarationsBlock` and `generateStyleStringFromSingleDeclarationsArray` for manipulating the style attributes...

**Comment by oliverklee** [comment]
This looks like either a bug in Hotmail (and should be reported there), or a bug in the input CSS (i.e., the author needs to fix their CSS to be look fine in Hotmail before they put it in Emogrifier). I don't see this as a (possible) responsibility of the Emogrifier package.
