### ISSUE TITLE
Normalizing test namespaces (and folder structure)?

### ISSUE THREAD

**Issue by zoliszabo** [MyIntervals/emogrifier#529]
Currently we have a couple of different namespace structures:

1. In `emogrifier/tests/Unit/EmogrifierTest.php`:
-> `namespace Pelago\Tests\Unit;`
2. In `emogrifier/tests/Unit/CssInlinerTest.php`:
-> `namespace Pelago\Emogrifer\Tests\Unit;`
3. In `emogrifier/tests/Unit/Emogrifier/HtmlProcessor/AbstractHtmlProcessorTest.php`:
-> `namespace Pelago\Tests\Unit\Emogrifier\HtmlProcessor;`
In ` emogrifier/tests/Unit/Emogrifier/HtmlProcessor/HtmlNormalizerTest.php`:
-> `namespace Pelago\Tests\Unit\Emogrifier\HtmlProcessor;`

I think we should decide between `Pelago\Emogrifier\Tests\Unit` and `Pelago\Tests\Emogrifier\Unit` as the prefix across all tests. Which one would you prefer?

Also, to keep sync between the `src` and `tests` folders, `CssInlinerTest.php` should be moved into the `Emogrifier` folder.

What do you think?

**Comment by oliverklee** [comment]
The `Emogrifier` class is outside the namespace we'd like to have after all cleanup is done (which is `Pelago\Emogrifier`.

Usually, the test namespace structure should match that of the tested production classes. In this cases, I'm for making an exception and put the `Emogrifier` test into `Pelago\Emogrifier\Tests\Unit` (so it technically has an extra `Emogrifier` in the namespace) so at least the test namespaces are proper PSR-4.

> I think we should decide between `Pelago\Emogrifier\Tests\Unit` and `Pelago\Tests\Emogrifier\Unit` as the prefix across all tests. Which one would you prefer?

Definitely `Pelago\Emogrifier\Tests\Unit`. I think I mixed it up by accident in the `CssInlinerTest`.

**Comment by oliverklee** [comment]
Moving to 4.0 (as this is the milestone where we will remove the original Emogrifier class).

**Comment by JakeQZ** [comment]
I just found there’s a typo in the `CssInlinerTest` namespace:

> <code>namespace Pelago\\<strong>Emogrifer</strong>\Tests\Unit;</code>

Simply correcting this to `Pelago\Emogrifier\Tests\Unit` didn’t seem right, as the other test classes all seem to be within `Pelago\Tests\Unit\…`.

For consistency with how their namespace (and location) corresponds to the class under test, it looks like the namespace for `CssInlinerTest` should be `Pelago\Tests\Unit\Emogrifier` and the file should also be moved into the `Emogrifier` subdirectory of where it is now.

> Definitely `Pelago\Emogrifier\Tests\Unit`. I think I mixed it up by accident in the `CssInlinerTest`.

But based on this comment, it's the other test classes that need changing, at least as far as the namespace name is concerned…
