### ISSUE TITLE
Add a HtmlMinifier or HtmlShrinker class (name pending)

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#551]
This class will have a method `removeInvisibleNodes`. Recommend to use this instead of the invisible node removal in Emogrifier.

Also remove the invisible node removal from the `CssInliner` class.

**Comment by jsnfwlr** [comment]
Could you not just have zaininnari/html-minifier as a dependency and use that?

**Comment by oliverklee** [comment]
@jsnfwlr Thanks for the suggestion!

The description of this ticket omitted that the responsibility of our `HtmlMinifier` should be removing nodes with `display: none;` and similar stuff, not removing whitespace. So `zaininnari/html-minifier` won't help in this regard. Thanks anyway for the suggestion!

**Comment by oliverklee** [comment]
Closed by #679.
