### ISSUE TITLE
Add additional PHPCS sniffs

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#574]
Following on from #563, there are currently 6 sniffs for PHPDoc from Squiz.Commenting.FunctionComment that are currently disabled, which require 'fixes' to the PHPDoc before they can be enabled.

Also noted there, [Slevomat Coding Standard](https://github.com/slevomat/coding-standard) provides further sniffs that may be desirable, notably [SlevomatCodingStandard.Arrays.TrailingArrayComma](https://github.com/slevomat/coding-standard#slevomatcodingstandardarraystrailingarraycomma-), but there may be others that a closer review of what is available would reveal.

**Comment by JakeQZ** [comment]
Also, possible additional sniffs suggested by recent PRs #572 and #573.

**Comment by oliverklee** [comment]
Yes, please! (Except for the parameter alignment, which would create busywork on potentially every change to the parameters.) And we should look at the necessary changes for each additional sniff.

**Comment by JakeQZ** [comment]
For the capital letter & full stop PHPDoc sniffs, we have a large number of @param and some @throws which don't have capitals or full stops (most of them it seems), so I would be inclined to continue to allow these for now rather than making a large number of changes (particularly as doing so may make maintaining Emogrifier and CssInliner in tandem more difficult).

What I'm specifically looking for is a sniff for this in the main PHPDoc comment, which Squiz.Commenting.FunctionComment doesn't seem to do...

**Comment by JakeQZ** [comment]
The only sniffs I could find for capitals and full stops in the PHPDoc short description don't distinguish between methods and properties, the latter for which we want to allow incomplete sentences.  (`Generic.Commenting.DocComment.ShortNotCapital` and, via `drupal/coder` which is out-of-date and incompatible with `php_codesniffer` 3.x, `Drupal.Commenting.DocComment.ShortFullStop`.)

**Comment by JakeQZ** [comment]
All of the potential sniffs alluded to here have either been added, or I was unable to find an off-the-peg sniff that would meet our requirements.  Whilst it is possible to write custom sniffs for PHPCS, the effort would probably outweigh the benefit for a relatively small project.

So I think this can be closed now.  We can always open a new issue if we come across specific sniffs that should be included.
