### ISSUE TITLE
nbsp is converted to plain space character

### ISSUE THREAD

**Issue by phena109** [MyIntervals/emogrifier#591]
Hi all,

I have tried something simple like `<div>A&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;B</div>` and emogrifier still convert those into space character. Reading the past issues like #95 and #98 I thought the issue is fixed. Is this only true for 1.x branch? I am using version 2.0.

If this cannot be fixed in some reasonable time, will there be a work around for that? I myself have done some search and replace for some special characters. But the thing is we are talking about a space character. My work around is probably a bit too aggressive or not accurate enough for that...

Please can someone help?

D

**Edit:**

Later I found out the replacement character is not a space character but character that's invisible. The rendering engine will still treat that like a non-space character. This in a way solved my original problem because I need things to take up the space for aesthetic purpose and that 'space' conversion did not gets in my way.

So my question will get updated to, "Will we get the freedom to retain the very specific `&nbsp;` 6 characters for code readability purpose?"

**Comment by oliverklee** [comment]
>  "Will we get the freedom to retain the very specific &nbsp; 6 characters for code readability purpose?"

In short: No. Internally, we don't have the HTML as text representation, but work on a DOM tree and then render it back to text. So this will not come. Sorry.
