### ISSUE TITLE
Why is [ converted to %5B after emogrify?

### ISSUE THREAD

**Issue by collizo4sky** [MyIntervals/emogrifier#593]
Say I have something like {{hello}}, it will be converted to %7B%7Bhello%7D%7D

What encoding is that?

FWIW I am using composer version ^1.0

**Comment by oliverklee** [comment]
@collizo4sky Does this also happen with version 1.2.1?

**Comment by collizo4sky** [comment]
From my composer.lock file, I think I am using V1.2.0. Let me update to 1.2.1 and see.

Brb

**Comment by collizo4sky** [comment]
Found the issue, this has nothing to do with emogrify. There was a urlencode at the top of the content being emogrified.
