### ISSUE TITLE
How to disable output <style>

### ISSUE THREAD

**Issue by Identity-labs** [MyIntervals/emogrifier#594]
Hi,

How to disable 

`<style type="text/css"><![CDATA[@media (max-width:900px) { ...`

In output rendering ?

Thx

**Comment by Identity-labs** [comment]
Yes, I want to remove all style node

**Comment by zoliszabo** [comment]
@Identity-labs Emogrifier does not currently offer an option to not include the non-inlineable styles into the final output. For details see code here: https://github.com/MyIntervals/emogrifier/blob/fb0cc85766dbd723b48f55cab2ad3381a668a521/src/Emogrifier.php#L420.

@oliverklee Would it make sense in your opinion to include such an option?

**Comment by oliverklee** [comment]
@Identity-labs The `style` tag includes the media queries. If it is removed, part of the CSS is missing. Why would you want to remove it?

(And if you don't need the media queries, I propose you remove them from your source CSS.)

> Would it make sense in your opinion to include such an option?

@zoliszabo I currently don't see why removing the node would make sense.

**Comment by Identity-labs** [comment]
The css use is the css of an application.
But we want tu render a part of the UI in mail.
The media queries is use for our cases

**Comment by oliverklee** [comment]
Then the `style` node will do not harm. As Emogrifier's main responsibility is "get HTML and CSS, and inline the given CSS in the HTML", I see it as the responsibility of the code providing the initial CSS to remove any CSS that should not be in the output.

Hence closing.

**Comment by Identity-labs** [comment]
Thx I will fork and add on option my self to disable call of $this->copyUninlineableCssToStyleNode($xmlDocument, $xPath, $cssRules['uninlineable']);
