### ISSUE TITLE
Optimization / cache

### ISSUE THREAD

**Issue by Identity-labs** [MyIntervals/emogrifier#598]
Hi,

Can CSS parsing be cached to improve processing time ?

We use emogrifier to make automated reporting and the css is the same every times.

Thx

**Comment by oliverklee** [comment]
Hi @Identity-labs, currently, the CSS is automatically cached for each Emogrifier instance, but not cross-instance. A pull request implementing this for (optimally, for the new `CssInliner` class) would be more than welcome!
