### ISSUE TITLE
Move the version number out of the class file(s)

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#636]
Historically, the current version number has been in the (at that time only) class file:
https://github.com/MyIntervals/emogrifier/blob/master/src/Emogrifier.php#L10

Now that we have more than one class file, I'd like to move it out of the class files. I currently see two options:

a) completely remove it as Composer already has the information which version is installed
b) move it to a `VERSION` or `RELEASE` file that contains nothing but the version number

@JakeQZ, @zoliszabo, @jjriv: What do you think?

**Comment by zoliszabo** [comment]
> Then... for visually inpsecting the source to see what version you're using, there is already the CHANGELOG

For visual inspection, while redundant, a `VERSION` file may be more intuitive for many. But again, it's extra maintenance. Don't know 🙂

>  For programatically testing the version, a `Package` class could be added with `const VERSION`, but I don't see any need for this right now, and it would be an extra maintenance step for each release.

Or even a package like https://github.com/Ocramius/PackageVersions can be used to programatically retrieve the installed version of Emogrifier.

**Comment by oliverklee** [comment]
Then let's completely remove the version number, and if someone complains, we can point them to https://github.com/Ocramius/PackageVersions.

Thanks for the thoughts on this!
