### ISSUE TITLE
Release version 2.1.0?

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#639]
In https://github.com/MyIntervals/emogrifier/pull/638#issuecomment-444890570, @TimWolla asked whether a 2.1.0 release really soon would be possible.

Originally, I had planned to finished the `CssInliner` class first and make the final API in place before people start using it first.

Instead, I could mark the `CssInliner` class as `@internal` for the time being and add a comment that the API is still apt to change and that people should not use the class yet. Then we could release version 2.1.0 really soon.

@JakeQZ @zoliszabo @jjriv What do you think?

**Comment by JakeQZ** [comment]
I agree it is too soon to say the `CssInliner` interface is final.  However, there have been a number of fixes and enhancements since `2.0.0` and as far as we are aware the development branch is stable.  Including `CssInliner` even though marked `@internal` would allow those who wished to to try the new interface, and may even attract some constructive feedback.

The alternative would be to make a `2.0.1` release with just the changes for PHP 7.3.  I don't have a strong opinion either way though my gut feeling is that the 'right' approach would be a `2.0.1` interim release as `2.1.0` isn't quite ready yet...

**Comment by oliverklee** [comment]
Emogrifier follows semantic versioning. As we have new features (but no breaking changes), we'll need to have a 2.1.0 release, not a 2.0.1 release.

**Comment by TimWolla** [comment]
> As we have new features (but no breaking changes), we'll need to have a 2.1.0 release, not a 2.0.1 release.

I believe @JakeQZ meant a 2.0.1 with only these two commits:

bf22f9e5efaa3802c28487f44e78203307d5f0b8
27cf8557f4d1ebd71ee5c4b4d6c20ab1ce18f262

The PHP 7.3 one from me is tagged as FEATURE, but it probably qualifies as a BUGFIX as well.

**Comment by zoliszabo** [comment]
Yes, I also like the `2.0.1` approach only with the PHP 7.3 compatibility changes.

OTOH releasing `CssInliner` (as `@internal`) may be beneficial to get valuable feedback, like it was mentioned above. Holiday season is coming, so hopefully there will be more time to work on Emogrifier :)

**Comment by zoliszabo** [comment]
I'm fine with it. 👍

**Comment by JakeQZ** [comment]
Go for it :)

I would suggest the buzzword (or buzzphrase) "new technology preview" (or at least perhaps "preview") for `CssInliner` :》

This would not affect plans for 3.0 when `Emogrifier` the class becomes deprecated, and certainly avoids 'version soup' (as well as extra faff).

**Comment by chrisdeeming** [comment]
@oliverklee a 1.2.2 or 1.3.0 version would be appreciated too.

**Comment by oliverklee** [comment]
> a 1.2.2 or 1.3.0 version would be appreciated too.

The 1.x branch ist not maintained anymore, and I'd like to spend as little time as possible with it. For getting the changes in the 2.x releases, I'd like people to use the 2.x releases instead.

**Comment by oliverklee** [comment]
To clarify things: I'm willing to do the 1.2.2 release if someone else takes care of backporting the fixes they'd like to have on the 1.2.x branch.

**Comment by oliverklee** [comment]
I've just tagged version 2.1.0 and created the release notes.
