### ISSUE TITLE
Update documentation to describe `CssInliner` instead of `Emogrifier`

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#695]
From 3.0, `Emogrifier` will be deprecated so the documention should detail how to use the `CssInliner` and family of classes rather than `Emogrifier`.

**Comment by JakeQZ** [comment]
I've updated a project to use `CssInliner` instead of `Emogrifier` without any problems.  The following code snippets may be useful to help describe the changes that would be needed to migrate from `Emogrifier` to `CssInliner`:

Old code using `Emogrifier`:
```php
$emogrifier = new Emogrifier($html);
$emogrifier->enableCssToHtmlMapping();
$html = $emogrifier->emogrify();
```

New code using `CssInliner` and family:
```php
$html = CssToAttributeConverter::fromDomDocument(
  HtmlPruner::fromDomDocument(
    CssInliner::fromHtml($html)->inlineCss('')->getDomDocument()
  )->removeInvisibleNodes()->getDomDocument()
)->convertCssToVisualAttributes()->render();
```

**Comment by oliverklee** [comment]
You can also reuse the same `$domDocument` instance (i.e., you'll need only one `getDomDocument()` call in total):

```php
$document = CssInliner::fromHtml($html)->inlineCss('')->getDomDocument();
HtmlPruner::fromDomDocument($document)->removeInvisibleNodes();
$html = CssToAttributeConverter::fromDomDocument($document)
  ->convertCssToVisualAttributes()->render();
```

By the way, why the `inlineCss('')` call with an empty string?

**Comment by JakeQZ** [comment]
> You can also reuse the same `$domDocument` instance

Good point.

> why the `inlineCss('')` call with an empty string?

In my case, all the CSS is contained in a `<style>` element within the HTML.  Though passing some `$css` as a parameter would probably make for a better example.

**Comment by oliverklee** [comment]
Would it make sense to have the argument for `inlineCss` optional for cases like that?

**Comment by JakeQZ** [comment]
> Would it make sense to have the argument for `inlineCss` optional for cases like that? (independent of the documentation)

It could be, though it's not a big deal.  Though for consistency with `Emogrifier` it should probably be optional - it was optional in the `Emogrifier` constructor.
