### ISSUE TITLE
Mark the utitlity classes as @internal?

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#713]
Hi @zoliszabo, @JakeQZ, should we mark the utility classes (`CssConcatenator` and `ArrayIntersector`) as `@internal` so it is clear that they might be removed, moved around or have their API changed without prior notice?

**Comment by JakeQZ** [comment]
This also occurred to me.

Though now #712 is committed, I don't envisage much likelyhood of that happening - they fulfill the purpose for which they were intended - even #668 is unlikely to have an impact.

OTOH, if there were to be a breaking change it would avoid the need for a new major version.  And anyone using them is likely to be fairly clued up and judicious about potentially breaking updates and take heed of such a notice - it doesn't prevent them being used.
