### ISSUE TITLE
HtmlPruner::removeInvisibleNodes could/should be better named?

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#717]
I propose `removeInvisibleElements`.

An element is a specific type of node.  In [documenation on MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/div), [W3C specifications](https://www.w3.org/TR/2011/WD-html5-20110525/elements.html) and [JavaScript](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement), nodes which are elements are always referred to as elements.

The nodes removed by the method are necessarily elements.  Therefore I think this method should be renamed before 3.0 is released and we are stuck with the name.  @oliverklee, @zoliszabo, would you agree?

**Comment by JakeQZ** [comment]
A secondary question on the `…Invisible…` part of the name – it doesn't remove elements with `visibility: hidden` but in fact removes those with `display: none`, so perhaps this could also be conveyed more clearly in the name… (though I can't think of great alternatives right now)?

**Comment by JakeQZ** [comment]
> A secondary question on the `…Invisible…` part of the name … (though I can't think of great alternatives right now)

I'm leaning towards `removeElementsWithDisplayNone` – it does what it says on the tin…

**Comment by oliverklee** [comment]
> `removeElementsWithDisplayNone`

Sounds good. Let's use this name.
