### ISSUE TITLE
Support `ci:php:lint` on Windows

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#740]
The Composer script for `php -l` uses a *nix-specific command and does not work on Windows.

We should find a way of allowing developers to run the whole of the `ci` script on whatever platform they're using.  (I'm guessing it works OK on macOS as that's Unix-based.  None of the other parts of the `ci` script have an issue on Windows.)

**Comment by SignpostMarv** [comment]
appears to work under gitbash.

**Comment by oliverklee** [comment]
@SignpostMarv Just wanted to let you know that I greatly appreciate you having started to contribute to Emogrifier with pull requests and ticket comments. :heart: Keep 'em coming! :cookie:

**Comment by JakeQZ** [comment]
> appears to work under gitbash.

I'm just using the command prompt in Windows, where all other commands work fine.  I could start using gitbash.  But I think this extra requirement would discourage people from contributing, so I'd prefer to have something that will work on all environments.
