### ISSUE TITLE
Add an editorconfig file

### ISSUE THREAD

**Issue by SignpostMarv** [MyIntervals/emogrifier#781]
Helps keep a consistent edit style for line endings & indentation across editors (i.e. your php files appear to have a tab size of 4, whereas the markdown files have a tab size of 2, and yaml is always spaces etc.)

**Comment by JakeQZ** [comment]
The source files (MD, PHP, or whatever) should always be indented with spaces to the desired ‘tab’ size, but this could be useful for supported IDEs to tell them how many spaces to insert when the TAB key is pressed.  (Automatically converting TABs to spaces upon save is an option in some IDEs, as is removing trailing spaces upon save.)
