### ISSUE TITLE
Investigate NonStaticSelfCall Psalm issue

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#792]
See https://github.com/MyIntervals/emogrifier/pull/778#discussion_r330914954.  It seems perhaps that Psalm is sporadically reporting false negatives with the `NonStaticSelfCall` check enabled.  We may need to disable this check in the Psalm config, before Psalm can be included in the Travis CI checks (#790).  It may perhaps be the case that this is fixed in a version we can't yet use due to dependency constrainsts (e.g. supporting PHP 7.0).

**Comment by oliverklee** [comment]
@JakeQZ Good research! It looks like there's already a PR for this: https://github.com/psalm/psalm-plugin-phpunit/pull/50

**Comment by JakeQZ** [comment]
There's a new release ([0.9.2](https://github.com/psalm/psalm-plugin-phpunit/releases/tag/0.9.2)) with the fix, but this would require a later version of Psalm (^3.6.2), which in turn would require a later version of `sebastian/diff` which is not compatible with PHPUnit 6.x - the latest version that still supports PHP 7.0.

So I would suggest this needs to wait until Emogrifier 5.0 (dropping PHP 7.0 support) to be resolved - unless Phive may be able to help with the dependency problem (we don't need Psalm to be able to run PHPUnit, and we only need to run Psalm against the current-minus-one PHP version).  Hence I've set 5.0 Milestone.

Additionally, later versions of Psalm introduce more checks, with additional code issues detected which would need investigating (though the issues reported could be added to the baseline temporarily), so updating Psalm is not a trivial change.

**Comment by oliverklee** [comment]
Phive might indeed help.

**Comment by oliverklee** [comment]
These are all resolved now. Closing.
