### ISSUE TITLE
track issues relating to raising the minimum php version to 7.1 or greater.

### ISSUE THREAD

**Issue by SignpostMarv** [MyIntervals/emogrifier#793]
- [x] raise minimum supported php version to 7.1
- [ ] update vimeo/psalm to latest version that supports 7.1
- - [ ] update psalm/plugin-phpunit to latest version that supports 7.1
- - [ ] remove `requireVoidReturnType="false"` from `psalm.xml`, re: 9d36ae4
- - [ ] review f6ea5a1, apply intended `@psalm-param` typehint & see if `MixedArgumentTypeCoercion` is resolved (or file issue with psalm)
- - [ ] review if updates resolve #792 without requiring code changes.
- - [ ] review if updates resolve the closure issue identified in #806 without requiring code changes
- [ ] update phpunit/phpunit to latest version that supports 7.179

**Comment by oliverklee** [comment]
We now require PHP >= 7.2. So this is all done now. Closing.
