### ISSUE TITLE
Investigate MixedArgument Psalm issue

### ISSUE THREAD

**Issue by SignpostMarv** [MyIntervals/emogrifier#806]
See https://github.com/MyIntervals/emogrifier/pull/802#pullrequestreview-298296128.

This set of issues pertains to `preg_replace_callback` support being improved (https://github.com/vimeo/psalm/commit/aa3df3f7a511ae4e12dedaa8f21552c47814fc5b#diff-4355ecf0bcc89fe8c145b64be0e02ddf) in a release of `vimeo/psalm`  that cannot be used until work on #793 begins.

**Comment by oliverklee** [comment]
These are all resolved now. Closing.
