### ISSUE TITLE
Add coveralls.io integration

### ISSUE THREAD

**Issue by SignpostMarv** [MyIntervals/emogrifier#807]
- [x] ~add coveralls to repo~ #808 
- [x] enable coveralls on organisation
- [x] add badge to readme

re: https://github.com/MyIntervals/emogrifier/pull/804#issuecomment-539230157

to avoid getting feature PRs that don't include coverage.

**Comment by JakeQZ** [comment]
Sounds like a good idea.  Like Psalm (until a week ago), something I know absolutely nothing about :)

**Comment by SignpostMarv** [comment]
just wanted to clarify that I've been holding off doing further work until this task was resolved, so I wouldn't end up PRing something that lowered the coverage, as per #804
