### ISSUE TITLE
Braket selector with `%` don't work

### ISSUE THREAD

**Issue by khoudj** [MyIntervals/emogrifier#815]
Braket selector with percent don't work :

```
table[width='80%'] {
   ...
}
```

Render :
```
<table width="80%"> 
   ...
</table>
```

Expected  :
```
<table width="80%" style="width:80%"> 
   ...
</table>
```

**Comment by oliverklee** [comment]
@khoudj Thanks for the feedback. Could you please retry with the latest release 3.0.0 and with the new `CssInliner` class?

**Comment by khoudj** [comment]
Thx @oliverklee for your quick answer. I'll try the latest release on this afternoon. I need to migrate project my projet. I's a Personal Composer dependance on many projects in my company.
I'll give you feedback ASAP

**Comment by khoudj** [comment]
@oliverklee the latest release 3.0.0 fix the problem. 
Very nice and THX for you help and your quick answer.
Best regard

**Comment by oliverklee** [comment]
@khoudj I'm happy to read this. Thanks for testing!
