### ISSUE TITLE
CssInliner with disableStyleBlocksParsing() returns error

### ISSUE THREAD

**Issue by DanielHitchen** [MyIntervals/emogrifier#823]
Hi,

Have recently updated Emogrifier to v3.0.0 and have everything working using the code:
```
$content = CssInliner::fromHtml($html)->inlineCss($css)->render();
```
but as soon as I add the **disableStyleBlocksParsing()** function, I get the below error:
```
Call to a member function inlineCss() on null
```
This is the updated code I'm using with the function applied:
```
$content = CssInliner::fromHtml($html)->disableStyleBlocksParsing()->inlineCss($css)->render();
```
Any help would be greatly appreciated.

**Comment by zoliszabo** [comment]
Hi @DanielHitchen, thanks for reporting this issue.

Indeed, the example in our README is not accurate, since the `disableStyleBlocksParsing()` method does not return the `CssInliner` instance after setting the option.

Please use it like this:
```php
$cssInliner = CssInliner::fromHtml($html);
$cssInliner->disableStyleBlocksParsing();
$cssInliner->inlineCss($css)->render();
```

**Comment by DanielHitchen** [comment]
@zoliszabo that's for you quick response - all working now :)
