### ISSUE TITLE
Normalize DOCTYPE?

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#858]
Noted in #831 is that `masterminds/html5` will always output the HTML5 DOCTYPE as `<!DOCTYPE html>`, i.e. uppercase `DOCTYPE` and lowercase `html`.

This is consistent with the [Polyglot Markup](https://www.w3.org/TR/html-polyglot/#doctype) recommendation for producers to [maximize support](https://www.w3.org/TR/html-polyglot/#dfn-robust-syntax).

For #831, we would, at least, need to change a test to expect the above DOCTYPE form in the output where the input is `<!DOCTYPE HTML>` (with uppercase `HTML`).

But should we, in any case, normalize the DOCTYPE as above?  I.e. always output `DOCTYPE` in uppercase (which we do anyway), and `html` in lowercase?  If so, should this be done when serializing (rendering) the DOM, parsing the HTML (when the DTD name is read into the [DOMDocumentType::$name property](https://www.php.net/manual/en/class.domdocumenttype.php#domdocumenttype.props.name)), or both (or even possibly in `fromDomDocument` and/or `getDomDocument`)?

**Comment by oliverklee** [comment]
Yes, let's normalize the DOCTYPE to `<DOCTYPE html>`.

Let's do it at the place where it the most simple. Officially, we do not support getting DOMDocuments from other sources anyway, so we might do it at any place.

**Comment by JakeQZ** [comment]
Simplest I imagine would to be to lowercase the `DOMDocumentType::$name` property.  To do this at `render()` time would create a (possibly undesirable) side-effect, thus we should do it at `fromHtml()` time.  That would also fit consistently with the fact that some other processing may occur at that stage, such as adding a `Content-Type`.
