### ISSUE TITLE
XHTML is not supported

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#859]
We do not support XHTML.  Void elements will be serialized (rendered) without a self-closing slash, e.g. `<br/>` will become `<br>`, and this is documented behaviour.

However, some test datasets use an XHTML document type.  E.g. `keepsExistingDocumentType` verifies that an XHTML document type would be preserved, despite the resultant HTML not being valid XHTML if it contains any void (empty content model) elements, and `convertsXmlSelfClosingTagsToNonXmlSelfClosingTag` even verifies that `<br/>` will be converted to `<br>` for both XHTML and non-XHTML document types.

I don't suggest we support XHTML: it is [not straightforward](https://stackoverflow.com/a/3145473/2511031) and would be of questionable benefit.

However, I find having tests involving XHTML document types misleading, and would suggest removing those DOCTYPEs from the test datasets.  We could employ [some other](https://www.w3.org/QA/2002/04/valid-dtd-list.html) supported DOCTYPE declarations instead.

What do you think?

**Comment by oliverklee** [comment]
I concur.
