### ISSUE TITLE
[Parse CSS Rules] @font-face should be uninlineable

### ISSUE THREAD

**Issue by aarongerig** [MyIntervals/emogrifier#869]
The `parseCssRules` method should not mark `@font-face` as inlineable. Otherwise, the font declaration simply gets removed since there is no DOM element found for the `@font-face` selector.

`@font-face`should be put into `<head><style type="text/css">...</style></head>` so fonts can be loaded and rendered.

WDYT?

**Comment by JakeQZ** [comment]
I agree, we should support this, thanks @aarongerig for raising it.

It could probably be handled similarly to how `@import` and `@charset` rules are - [these are filtered out of the input CSS](https://github.com/MyIntervals/emogrifier/blob/v3.1.0/src/Emogrifier/CssInliner.php#L476) and [put back in at the end](https://github.com/MyIntervals/emogrifier/blob/v3.1.0/src/Emogrifier/CssInliner.php#L1065).

We are considering using a 3rd party library for parsing CSS (#544), which may help, but TBH I don't expect this to happen any time soon.

In the meantime, if you would like to submit a PR for this specific issue, it would be very much appreciated (and hopefully the links above will be pointers for where to start)... the code in this area looks a bit messy (I wrote some of it) so any other improvements you could suggest would also be welcome...

**Comment by aarongerig** [comment]
@JakeQZ Thanks for the quick response! Sure, I'll give it a try with the PR. 👍🏻
