### ISSUE TITLE
Switch to php-parallel-lint/php-parallel-lint

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#882]
https://packagist.org/packages/grogy/php-parallel-lint

This package is abandoned and no longer maintained. The author suggests using the php-parallel-lint/php-parallel-lint package instead.

**Comment by JakeQZ** [comment]
LOL.  This will be the second time this has been moved within a year.

On a side-note, I have a fork of an abandoned (but reasonably well-known) package/repository with literally half a dozen PRs waiting to be included.  Any advice?

**Comment by JakeQZ** [comment]
PS. We do, I think, need to support Windows as a dev environment, to encourage contribution.

**Comment by oliverklee** [comment]
> On a side-note, I have a fork of an abandoned (but reasonably well-known) package/repository with literally half a dozen PRs waiting to be included. Any advice?

Apart from pining the developer(s) in the PR, no.

**Comment by JakeQZ** [comment]
> Apart from pinging the developer(s) in the PR every now and then, no.

It's literally marked as abandoned now.  So someone else will have to take ownership using their own fork, and presumably make a separate package name as has happened here.

**Comment by oliverklee** [comment]
Fixed by 11c91702ea9690e454df8373602d6715be789fc8.
