### ISSUE TITLE
Allow PHP 8 installs

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#916]
… a bit like this (but with GitHub actions): https://github.com/tijsverkoyen/CssToInlineStyles/pull/198/files

**Comment by JakeQZ** [comment]
Is the PHP 8 alpha available via GitHub actions now?

Yes please, let's be on the ball about this and future PHP versions, so we are not having to make patch releases to support a new PHP version :)

**Comment by oliverklee** [comment]
> Is the PHP 8 alpha available via GitHub actions now?

Yes, the setup PHP action [provides the PHP 8 nightly](https://github.com/marketplace/actions/setup-php-action#tada-php-support).
