### ISSUE TITLE
X Data Providers

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#921]
X = cross (product?) = combine datasets in all possible combinations

Previously I've added a couple of tests that involve doing something like this.

https://github.com/T-Regx/CrossDataProviders could tidy that up.

No urgency, but something to consider, particularly if a situation comes up in future that fits the bill.

**Comment by JakeQZ** [comment]
This has been partly addressed by #1000.

There are some other instances where we only want to test a subset of the matrix (otherwise the number of tests becomes way to large), but would require a feature request with `rawr/cross-data-providers`.

**Comment by oliverklee** [comment]
Should we then close this issue?

**Comment by JakeQZ** [comment]
> Should we then close this issue?

OK.
