### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by JakeQZ** [MyIntervals/emogrifier#954]
https://github.com/MyIntervals/emogrifier/actions/runs/434894580

PHIVE now gives the following error when run to update PHPUnit:

> Call to undefined function PharIo\Phive\xdebug_disable()

A bit of research suggests [the problem is introduced](https://github.com/magento/magento2/issues/28961#issuecomment-734340591) [by XDebug 3.0](https://xdebug.org/docs/upgrade_guide).

As a temporary solution, would we be able to run `pecl install -f xdebug-2.9.8` in the GitHub action?

**Comment by oliverklee** [comment]
Possible the PHP setup build also allows specifying the XDebug version.

Or maybe we can disable XDebug altogether (as we are currently not using it yet).
