### ISSUE TITLE
Inline CSS on HTML elements within comments?

### ISSUE THREAD

**Issue by jonathanstegall** [MyIntervals/emogrifier#962]
Is it possible for emogrifier to respond to HTML elements that are within an HTML comment and give them inline CSS rules? For example, email developers can use such comments to provide elements that only Outlook can see.

At least by default, with code like this, the elements that are outside the comments will get inline styles, but the ones inside the comments will not.

```html
<div class="o-columns o-header">
    <!--[if mso]>
        <table role="presentation" width="100%" class="o-columns o-header">
            <tr>
                <td class="o-column a-logo">
    <![endif]-->
    <div class="o-column a-logo">
        <div>
            [logo goes here]
        </div>
    </div>
    <!--[if mso]>
                </td>
                <td class="o-column m-support-cta">
    <![endif]-->
    <div class="o-column m-support-cta">
        <div>
        [support goes here]
        </div>
    </div>
    <!--[if mso]>
                </td>
            </tr>
        </table>
    <![endif]-->
</div>
```

Is there an option, or another way that this can be enabled?

**Comment by oliverklee** [comment]
@jonathanstegall Emogrifier currently does not support this, and I'm not sure we should (as this relies on non-standard HTML).

As a workaround, you could replace the two marker comments with the `mso` condition with something else first, then emogrify your HTML, and then re-replace the comments. That would be the IMHO cleanest approach.

**Comment by jonathanstegall** [comment]
@oliverklee thank you, I think that does work. What appears to be working for me, in case it's helpful for anyone else, is this:

```html
<div class="o-columns o-header">
    [outlook]
        <table role="presentation" width="100%" class="o-columns o-header">
            <tr>
                <td class="o-column a-logo">
    [/outlook]
    <div class="o-column a-logo">
        <div style="padding:10px;font-size:14px;line-height:18px;text-align:left;">
            [logo goes here]
        </div>
    </div>
    [outlook]
                </td>
                <td class="o-column m-support-cta">
    [/outlook]
    <div class="o-column m-support-cta">
        <div style="padding:10px;font-size:14px;line-height:18px;text-align:left;">
        [support goes here]
        </div>
    </div>
    [outlook]
                </td>
            </tr>
        </table>
    [/outlook]
</div>
```

Then where I'm calling Emogrifier, I do this:

```php
$html = CssInliner::fromHtml( $html )->inlineCss( $css )->render();
$html = str_replace( '[outlook]', '<!--[if mso]>', $html );
$html = str_replace( '[/outlook]', '<![endif]-->', $html );
```

As far as I can tell, this renders the HTML with the inline styles on the Outlook tables correctly, and it also renders the Outlook-focused comments correctly.

**Comment by oliverklee** [comment]
@jonathanstegall I'm glad to read that you could solve this.

Would you be willing to create a pull request to add this solution to the README? Maybe this can help other as well.
