### ISSUE TITLE
Move PHPUnit back from PHIVE to Composer

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#983]
This would allow tools like Psalm or Rector to also work on the tests (as they need to be able to autoload the PHPUnit classes).

**Comment by JakeQZ** [comment]
I was going to say that this would also mean the workaround to install a different version of PHPUnit for PHP 7.2 than later versions, while PHIVE does not (yet) support selection of a compatible version based on PHP version, would not be required.

However, I just checked, and now support for PHP 7.1 has been dropped, PHPUnit 8.x can be used for all supported PHP versions, so we could now remove that workaround anyway.  Though if we switch back to Composer, that becomes a non-issue, and we can also continue to use PHPUnit 9.x with PHP versions it supports.
