### ISSUE TITLE
Stop version-controlling the tool PHARs?

### ISSUE THREAD

**Issue by oliverklee** [MyIntervals/emogrifier#984]
https://github.com/MyIntervals/emogrifier/pull/968#issuecomment-815341117:

> Feedback from https://github.com/phar-io/phive/issues/296 suggests we have an "interesting use case".  However feedback from https://github.com/phar-io/phive/issues/295 indicates PHIVE currently does not support installing a version necessarily compatible with the calling environment.

https://github.com/MyIntervals/emogrifier/pull/968#issuecomment-815605094:
> Let's see what the rest of the PHP developer crowd thinks. :-)
>
> I have created a Twitter poll for this: https://twitter.com/oliklee/status/1380082284200595457

**Comment by JakeQZ** [comment]
cross-reference: discussion at #1174
